language: node_js
node_js:
  - "lts/*"
cache: npm
script:
  - |
    # Run test script
    npm run test-ci
after_script:
  - |
    # Upload coverage to coveralls
    if [[ -d .nyc_output ]]; then
      npm install --save-dev coveralls@2
      nyc report --reporter=text-lcov | coveralls
    fi
